version: "3.8"

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: yarn storybook
    ports:
      - "6006:6006"
    volumes:
      - .:/workspace/app:delegated
      - ./package.json:/workspace/package.json
      - ./yarn.lock:/workspace/yarn.lock
      - node_modules:/workspace/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
