version: "3.8"

# docker-compose build --no-cache

x-common: &common
  build:
    context: ./
    target: base
  working_dir: /app
  volumes:
    - .:/app
    - node_modules:/app/node_modules

x-env-development: &env-development
  environment:
    - NODE_ENV=development
    - BABEL_ENV=development

services:
  yarn:
    <<: *common
    <<: *env-development
    entrypoint: yarn

  storybook:
    <<: *common
    <<: *env-development
    ports:
      - "6006:6006"
    command: yarn storybook

volumes:
  node_modules:
