version: "3.8"

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=development
    ports:
      - "6006:6006"
    volumes:
      - .:/workspace/app
      # - node_modules:/workspace/node_modules
    environment:
      - NODE_ENV=development
    command: yarn storybook

# volumes: 
#   node_modules:
